### ISSUE TITLE
Many Question!

### ISSUE THREAD

**Issue by Zinc-Exclamation** [eaglePB2/eaglePB2#15]
I found your archive of Plazma Burst FTTP and Plazma Burst 2, and I was curious how you obtained these!
your collection is amazing!
Is the collection Complete with all versions?
how many of them are Official, and how many are Modded?

Thanks!

**Comment by eaglePB2** [comment]
Hi！

1) Obtaining those are somewhat "painful" -> had to wayback machine everything, usage of google dork and more research and avoiding phishing website link, thus some inspect element skills to "force" download the swf file etc, yeah, that's a lot of things had to done with :D
Also, I had only to save the versions which significantly changes something, so for versions 1.34 to 1.35 I would just keep 1.35 as those two versions doesn't have significant updates.

2) Currently this collection would never complete with all versions as eric would hide/haven't publish few versions of them before :3
 
3) Also, currently all of them are "official", modded version would be in another repository which collab with Nyove of building a modded PB2 launcher to do it.

**Comment by Zinc-Exclamation** [comment]
Thank you for your hard work!
